name: 🐞 Bug report
description: Report an issue
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Bug description
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) is **required**, otherwise the issue might be closed without further notice. [**Why & How?**](https://antfu.me/posts/why-reproductions-are-required)
      placeholder: Reproduction
    validations:
      required: true
  - type: dropdown
    id: OS
    attributes:
      label: Used OS
      description: Select the used OS
      options:
        - IOS
        - Android
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: version
      description: |
        Please add the app version. If it's not provided this issue will be ignored and closed.
        Navigate to settings on the impacthubwallet app and read the myappversion.
      placeholder: Reproduction
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
          required: true
